[package]
name = "TestU01Drv"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"  # (keep in sync with `ci.yaml`)
description = "CLI driver for the TestU01 random number testing library"
repository = "https://github.com/SludgePhD/TestU01Drv"
categories = ["mathematics", "algorithms"]
keywords = ["prng", "rng", "statistics", "correlation"]
license-file = "TestU01-1.2.3/COPYING"

[build-dependencies]
cc = "1.2.59"

[dependencies]
larpa = "0.1.1"
