[package]
name = "TestU01Drv"
version = "0.1.0"
edition = "2024"
description = "CLI driver for the TestU01 random number testing library"
categories = ["mathematics", "algorithms"]
keywords = ["prng", "rng", "statistics", "correlation"]
license-file = "TestU01-1.2.3/COPYING"

[build-dependencies]
cc = "1.2.59"

[dependencies]
larpa = "0.1.1"
